# Generated by Django 6.0 on 2026-02-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('abbreviation', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=400)),
                ('address', models.TextField()),
                ('type', models.CharField(choices=[('prospect', 'Prospect'), ('Customer', 'customer')], default='prospect', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField()),
                ('email', models.CharField(max_length=400)),
                ('role', models.CharField(blank=True, max_length=250, null=True)),
                #('is_deleted', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='company.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('company_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=60)),
                ('status', models.CharField(blank=True, choices=[('تازه وارد', 'New'), ('تایید شده', 'Qualified'), ('تماس گرفته شده', 'Contacted'), ('غیر قابل پیگیری', 'DisQualified')], default='تازه وارد', verbose_name='status')),
                ('source', models.CharField(choices=[('google_ads', 'Google Ads'), ('content_marketing', 'Content Marketing'), ('referral', 'Refferal')], default='google_ads', max_length=200)),
                ('is_converted', models.BooleanField(blank=True, default=False)),
                ('converted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
